# Generated by Django 6.0.6 on 2026-07-05 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EpisodeWatchStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_id", models.IntegerField()),
                ("show_title", models.CharField(max_length=200)),
                ("season_number", models.IntegerField()),
                ("episode_number", models.IntegerField()),
                ("episode_title", models.CharField(blank=True, max_length=200)),
                ("watched", models.BooleanField(default=False)),
                ("date_watched", models.DateTimeField(blank=True, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episode_status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["show_id", "season_number", "episode_number"],
                "unique_together": {
                    ("user", "show_id", "season_number", "episode_number")
                },
            },
        ),
        migrations.CreateModel(
            name="WatchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_id", models.IntegerField()),
                (
                    "media_type",
                    models.CharField(
                        choices=[("movie", "Movie"), ("tv", "TV Show")], max_length=10
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("watched", models.BooleanField(default=False)),
                ("watchlist", models.BooleanField(default=False)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_updated"],
                "unique_together": {("user", "media_id", "media_type")},
            },
        ),
    ]
